# Generated by Django 2.0.7 on 2020-12-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='summary',
            field=models.TextField(default='this is cool!'),
        ),
    ]
